all:
	make -C antknn/
	make -C btfreplay/
	make -C domworld/
	make -C fishknn/
	make -C fishlr/
	make -C fishreynolds/
	make -C learnedants/
	make -C tutorial/
	make -C twostateants/
clean:
	make -C antknn/ clean
	make -C btfreplay/ clean
	make -C domworld/ clean
	make -C fishknn/ clean
	make -C fishlr/ clean
	make -C learnedants/ clean
	make -C tutorial/ clean
	make -C twostateants/ clean
